// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yatbqlkbsenzntijxpaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdGJxbGtic2Vuem50aWp4cGFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDExNjEsImV4cCI6MjA2NzI3NzE2MX0.80tI1I4Rb8okn4jIoF5ymdkvt63ZPkaBnWtD1yTK2HU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});